/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgregarRouteImport } from './routes/agregar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as EditarIdRouteImport } from './routes/editar.$id'
import { Route as ImportarArchivoRouteImport } from './routes/importar.archivo'
import { Route as ImportarTextoRouteImport } from './routes/importar.texto'
import { Route as RecetaIdRouteImport } from './routes/receta.$id'
import { Route as RecetaNuevaRouteImport } from './routes/receta.nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgregarRoute = AgregarRouteImport.update({
  id: '/agregar',
  path: '/agregar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarIdRoute = EditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarArchivoRoute = ImportarArchivoRouteImport.update({
  id: '/importar/archivo',
  path: '/importar/archivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarTextoRoute = ImportarTextoRouteImport.update({
  id: '/importar/texto',
  path: '/importar/texto',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetaIdRoute = RecetaIdRouteImport.update({
  id: '/receta/$id',
  path: '/receta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetaNuevaRoute = RecetaNuevaRouteImport.update({
  id: '/receta/nueva',
  path: '/receta/nueva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/editar/$id': typeof EditarIdRoute
  '/importar/archivo': typeof ImportarArchivoRoute
  '/importar/texto': typeof ImportarTextoRoute
  '/receta/$id': typeof RecetaIdRoute
  '/receta/nueva': typeof RecetaNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/editar/$id': typeof EditarIdRoute
  '/importar/archivo': typeof ImportarArchivoRoute
  '/importar/texto': typeof ImportarTextoRoute
  '/receta/$id': typeof RecetaIdRoute
  '/receta/nueva': typeof RecetaNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/editar/$id': typeof EditarIdRoute
  '/importar/archivo': typeof ImportarArchivoRoute
  '/importar/texto': typeof ImportarTextoRoute
  '/receta/$id': typeof RecetaIdRoute
  '/receta/nueva': typeof RecetaNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agregar'
    | '/auth'
    | '/perfil'
    | '/editar/$id'
    | '/importar/archivo'
    | '/importar/texto'
    | '/receta/$id'
    | '/receta/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agregar'
    | '/auth'
    | '/perfil'
    | '/editar/$id'
    | '/importar/archivo'
    | '/importar/texto'
    | '/receta/$id'
    | '/receta/nueva'
  id:
    | '__root__'
    | '/'
    | '/agregar'
    | '/auth'
    | '/perfil'
    | '/editar/$id'
    | '/importar/archivo'
    | '/importar/texto'
    | '/receta/$id'
    | '/receta/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgregarRoute: typeof AgregarRoute
  AuthRoute: typeof AuthRoute
  PerfilRoute: typeof PerfilRoute
  EditarIdRoute: typeof EditarIdRoute
  ImportarArchivoRoute: typeof ImportarArchivoRoute
  ImportarTextoRoute: typeof ImportarTextoRoute
  RecetaIdRoute: typeof RecetaIdRoute
  RecetaNuevaRoute: typeof RecetaNuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agregar': {
      id: '/agregar'
      path: '/agregar'
      fullPath: '/agregar'
      preLoaderRoute: typeof AgregarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$id': {
      id: '/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof EditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar/archivo': {
      id: '/importar/archivo'
      path: '/importar/archivo'
      fullPath: '/importar/archivo'
      preLoaderRoute: typeof ImportarArchivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar/texto': {
      id: '/importar/texto'
      path: '/importar/texto'
      fullPath: '/importar/texto'
      preLoaderRoute: typeof ImportarTextoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receta/$id': {
      id: '/receta/$id'
      path: '/receta/$id'
      fullPath: '/receta/$id'
      preLoaderRoute: typeof RecetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receta/nueva': {
      id: '/receta/nueva'
      path: '/receta/nueva'
      fullPath: '/receta/nueva'
      preLoaderRoute: typeof RecetaNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgregarRoute: AgregarRoute,
  AuthRoute: AuthRoute,
  PerfilRoute: PerfilRoute,
  EditarIdRoute: EditarIdRoute,
  ImportarArchivoRoute: ImportarArchivoRoute,
  ImportarTextoRoute: ImportarTextoRoute,
  RecetaIdRoute: RecetaIdRoute,
  RecetaNuevaRoute: RecetaNuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
